#!/bin/bash


#-----------------------TESTING-----------------------

#ID=id:chatcmpl-79T1EkA8nPM5AQbeNG3x0QRTPfp95 --- 04/26/23/08:34
#ID=$(echo "$ID" | sed 's/ ---.*//')
#echo "$ID"

#-----------------------VARIABLES-----------------------
vers="1.6.6"

blue=$(tput setaf 4)
yellow=$(tput setaf 11)
red=$(tput setaf 1)
green=$(tput setaf 2)
normal=$(tput sgr0)
magneta=$(tput setaf 5)

h="\n${blue}Usage: glados \"Explain quantum computing in simple terms\"${yellow}\n\nCommand arguments:${normal}\n'-h'   -   To access this prompt\n'-c'   -   To access GLaDOS chat mode\n'-r'   -   To reset the chat\n'-n'   -   To prevent sending the name on first chat\n'-v'   -   To see the current verion\n'-u'   -   To update GLaDOS\n'-s'   -   To execute a shell command (EXPERIMENTAL!)\n\n${yellow}Chat mode arguments:  (Literally, just type them inside chat mode)${normal}\n'-q'   -   To quit GLaDOS chat mode\n'-h'   -   To access this prompt\n\n${green}More functions coming soon${normal}"

#-----------------------FUNCTIONS-----------------------
function reset() {
if [ -f ~/.config/tgpt/config.txt ]; then
	printf "\n${red}Are you sure you want to reset the chat, it will be DELETED!\n\n${normal}Are you sure? [y/N]: "
	read C && C=$(echo "$C" | tr '[:upper:]' '[:lower:]')
	if [ "$C" = "y" ] || [ "$C" = "yes" ]; then
		printf "\n${red}RESETTING...\n"
		rm -f ~/.config/tgpt/config.txt
		if [ -n "$T" ] && [ -z $OP_C ]; then
			cols=$(tput cols)
			printf "\n"
			tput setaf 1 && for ((i=0; i<$cols; i++)); do printf "${magneta}-"; done && printf "\n"
		fi
	else
		printf "\n${green}CANCELLED\n"
		if [ -n "$T" ] && [ -z $OP_C ]; then
			cols=$(tput cols)
			printf "\n"
			tput setaf 1 && for ((i=0; i<$cols; i++)); do printf "${magneta}-"; done && printf "\n"
		fi
	fi
elif [ "$OP_R" = true ] && [ ! -f ~/.config/tgpt/config.txt ]; then
	printf "\n${red}There's no chat to reset!\n"
	if [ -n "$T" ] && [ -z $OP_C ]; then
		cols=$(tput cols)
		printf "\n"
		tput setaf 1 && for ((i=0; i<$cols; i++)); do printf "${magneta}-"; done && printf "\n"
	fi
fi
printf "${normal}"
}

#-----------------------ARGS CHECKER-----------------------
ARGS=$(getopt -o rcnhvuso --long uninstall -n "$0" -- "$@" 2>/dev/null)
if [ $? -ne 0 ] && [ "$1" != "--flags" ]; then
	printf "\n${red}Command Not Found!\n${blue}Use '-h' to get more help\n"
	exit
fi

eval set -- "$ARGS"
while true; do
	case "$1" in
		-r)
			OP_R=true
			shift;;
		-c)
			OP_C=true
			shift;;
		-n)
			OP_N=true
			shift;;
		-h)
			OP_H=true
			shift;;
		-v)
			install_location=$(which glados | sed 's/\/glados//')
			if [ "$install_location" = /usr/local/bin ]; then
				install_type="Global"
			else
				install_type="Local"
			fi
			printf "\n${blue}Current installation type${normal}: ${yellow}$install_type\n\n${blue}GLaDOS verion${normal}:${yellow} $vers\n${blue}GPT version${normal}:${yellow} $(gpt -v)${normal}\n"
			exit
			shift;;
		-u)
			OP_U=true
			shift;;
		-s)
			OP_S=true
			shift;;
		-o)
			OP_O=true
			shift;;
		--uninstall)
			OP_UN=true
			shift;;
		--)
			shift;
			break;;
	esac
done

#-----------------------TEXT CHECKS-----------------------
T="$@"
if [ -z "$T" ] && [ -z "$OP_C" ] && [ -z "$OP_H" ] && [ -z "$OP_R" ] && [ -z "$OP_U" ] && [ -z "$OP_S"] && [ -z "$OP_O" ]; then
	printf "\n${red}You have to write some text!\n${blue}Example: glados \"Explain quantum computing in simple terms\"\nUse '-h' to get more help${normal}\n"
	exit
elif [ "$OP_S" = true ] && [ -z "$T" ]; then
	printf "\n${red}You have to write some text!\n${blue}Example: glados -s \"How to update system\"\nUse '-h' to get more help${normal}\n"
	exit
elif [ "$OP_O" = true ] && [ -z "$T" ]; then
	printf "\n${red}You have to write some text!\n${blue}Example: glados -o \"How to make a https request in php\"\nUse '-h' to get more help${normal}\n"
	exit
fi

#-----------------------HELP PROMPT-----------------------
if [ "$OP_H" = true ] && [ -z "$OP_C" ]; then
	printf "$h\n"
	exit
fi

#-----------------------RESET FUNCNCTION-----------------------
if [ "$OP_R" = true ]; then
reset
	if [ -z "$OP_C" ] && [ -z "$T" ]; then
		exit
	fi
sleep 2
fi

#-----------------------NETWORK CHECK-----------------------
if ! ping -q -c1 google.com &>/dev/null; then
		printf "\n${red}You don't have internet connection! Please reconnect and try again\n\n"
		exit
fi

#-----------------------UPDATER-----------------------
if [ "$OP_U" = true ]; then
	stty -echo
	printf "\n"

	#Check Language
	if [ $(locale | grep "LANG=en_US.UTF-8") ]; then
		Downloads_Folder="Downloads"
	elif [ $(locale | grep "LANG=ca_ES.UTF-8") ]; then
		Downloads_Folder="Baixades"
	else
		mkdir $HOME/"TMP_DELETE-ME"
		Downloads_Folder="TMP_DELETE-ME"
	fi

	#Check If Sudo
	if [[ $EUID -ne 0 ]]; then
		sudo="false"
		user=$USER
	else
		sudo="true"
		user=$SUDO_USER
	fi

	#Check Install Location
	install_location=$(which glados | sed 's/\/glados//')
	if [ "$install_location" = /usr/local/bin ]; then
		install_type="Global"
	else
		install_type="Local"
	fi

	if [ "$install_type" = "Global" ] && [ "$sudo" = "false" ]; then
		printf "${red}This Function Must Be Run As SUDO (Because The Program Is Installed Globally)\n" 
		stty echo
		exit
	fi

	#Cleanup funcions
	function cleanup {
		cd $directory_path
		rm -r -f ./tgpt 2>/dev/null
		rm -r -f ./glados 2>/dev/null
		cd
		printf "${blue}Cleaning Up...  ${green}Done!\n"
	}
	
	function cleanup_sig {
		cd $directory_path
		rm -r -f ./tgpt 2>/dev/null
		rm -r -f ./glados 2>/dev/null
		cd
		stty echo
		printf "\n${magneta}----------------------------------\n\n${blue}User Ordered SIGINT. ${yellow}Cleaning Up...\n"
		exit
	}
	
	function cleanup_fail {
		cd $directory_path
		rm -r -f ./tgpt 2>/dev/null
		rm -r -f ./glados 2>/dev/null
		cd
		stty echo
		printf "\n${magneta}----------------------------------\n\n${red}Installation Failed! ${yellow}Cleaning Up...\n"
		exit
	}
	
	#Give Installation Type Chance
	printf "${blue}Current Installation Type Is: $install_type\n"
	if [ "$sudo" = true ]; then
		stty echo
		printf "${normal}Do You Want To Change It? [y/N]: " && read C && C=$(echo "$C" | tr '[:upper:]' '[:lower:]') && printf "\033[1A\033[2K"
		stty -echo
		if [ "$C" = "y" ] || [ "$C" = "yes" ]; then
			if [ "$install_type" = Global ]; then
				install_location=$HOME/.local/bin
				printf "\033[1A\033[2K${blue}New Installation Type Is: Local\n"
			else
				install_location=/usr/local/bin
				printf "\033[1A\033[2K${blue}New Installation Type Is: Global\n"
			fi
		fi
	fi
	printf "${magneta}----------------------------------\n\n"

	#Prepare
	directory_path="$HOME/Downloads"
	cd $directory_path
	trap cleanup_sig SIGINT
	printf "${yellow}Getting Latest Release Of TGPT..."
	if git clone -q https://github.com/aandrew-me/tgpt $directory_path/tgpt 2>/dev/null; then
		printf "\033[2K\r${green}Successfully Got Lastest Release Of TGPT!\n"
	else
		printf "\033[2K\r${red}Failed To Get Lastest Release Of TGPT!\n"
		cleanup_fail
	fi
	stty echo
	printf "${yellow}Getting Lastest Release Of GLaDOS..." && printf "${red}  Authoritzation needed!\n${blue}"
	if git clone -q https://GamerBlue208@github.com/GamerBlue208/GLaDOS $directory_path/glados 2>/dev/null; then
		printf "\033[1A\033[2K\033[1A\033[2K\r${green}Successfully Got Lastest Release Of GLaDOS!\n"
	else
		printf "\033[1A\033[2K\033[1A\033[2K\r${red}Failed To Get Lastest Release Of GLaDOS!\n"
		cleanup_fail
	fi
	stty -echo
	cd ./tgpt
	printf "${magneta}----------------------------------\n\n"

	#Cut Parts
	printf "${yellow}Modifying TGPT..."
	sed -i 's/"tgpt", //g' "./main.go" 2>/dev/null
	sed -i '/\/\/ Print the Question/,+9d' "./functions.go" 2>/dev/null
	printf "\033[2K\r${green}Successfully Modified TGPT!\n"

	#Change Name Of Old Version
	if [[ -e "$install_location/gpt" ]]; then
  		mv "$install_location/gpt" "/$install_location/gpt-old" 2>/dev/null
	else
		rm "$install_location/gpt-old" 2>/dev/null && mv "$install_location/gpt" "$install_location/gpt-old" 2>/dev/null
	fi

	#Build
	printf "${yellow}Building TGPT..."
	if go build -o $install_location/gpt 2>/dev/null; then 
		printf "\033[2K\r${green}Successfully Built TGPT!\n"
	else
		printf "\033[2K\r${red}Failed To Build TGPT!\n"
		mv "$install_location/gpt-old" "/$install_location/gpt" 2>/dev/null
		cleanup_fail
	fi
	cd .. && cd ./glados && chmod +x ./glados && mv ./glados $install_location 2>/dev/null
	printf "${magneta}----------------------------------\n\n"

	#Delete Old Swap Files
	if [ "$C" = "y" ] || [ "$C" = "yes" ]; then
		if [ "$install_type" = Global ]; then
			rm /usr/local/bin/glados 2>/dev/null
			rm /usr/local/bin/gpt 2>/dev/null
			rm /usr/local/bin/gpt-old 2>/dev/null
			sudo chown $user ~/.local/bin/glados && sudo chown $user ~/.local/bin/gpt && sudo chown overlord ~/.local/bin/gpt-old 2>/dev/null
			ln -s $HOME.local/bin/glados /usr/local/sbin 2>/dev/null
			ln -s $HOME/.local/bin/gpt /usr/local/sbin 2>/dev/null
		else
			rm $HOME/.local/bin/glados 2>/dev/null
			rm $HOME/.local/bin/gpt 2>/dev/null
			rm $HOME/.local/bin/gpt-old 2>/dev/null
			rm /usr/local/sbin/glados 2>/dev/null
			rm /usr/local/sbin/gpt 2>/dev/null
		fi
	fi

	#Clean Up
	if [ $Downloads_Folder="TMP_DELETE-ME" ]; then
		cd
		rm -rf "TMP_DELETE-ME"
	fi
	printf "${green}Installation Succeded!\n"
	cleanup
	printf "${blue}\nExiting...\n"
	stty echo
	export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$HOME/.local/bin"
	exit

	#Password For GLaDOS repo: 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
fi

#-----------------------UNINSTALLER-----------------------
if [ "OP_UN" = true ]; then
	#pfffffff, code
	exit
fi

#-----------------------SHELL COMMANDS-----------------------
if [ "$OP_S" = true ]; then
	gpt -s "$T"
	exit
fi

#-----------------------CODE-----------------------
if [ "$OP_O" = true ]; then
	gpt -c "$T"
	exit
fi

#-----------------------CHAT MODE FUNCTION-----------------------
if [ "$OP_C" = true ]; then
	stty -echo
	clear
	printf "${green}Welcome to GLaDOS chat mode! Type \"-h\" to know the commands${normal}\n\n"
	if [ "$OP_N" = true ] && { [ "$OP_R" = true ] || [ ! -f ~/.config/tgpt/config.txt ]; }; then
		if [ -n "$T" ]; then
			printf  "\n\e[0;1m>> \e[0m" && printf "${blue}$T${normal}\n\n"
			gpt "$T"
		else
			printf "\n"
			gpt "hi"
		fi
	elif [ -f ~/.config/tgpt/config.txt ]; then
		if [ -n "$T" ]; then
			printf  "\n\e[0;1m>> \e[0m" && printf "${blue}$T${normal}\n\n"
			gpt "$T"
		fi
	elif [ ! -f ~/.config/tgpt/config.txt ]; then
		if [ -n "$T" ]; then
			printf  "\n\e[0;1m>> \e[0m" && printf "${blue}$T${normal}\n\n"
			gpt "Your name is now GLaDOS and mine is $USER, $T"
		else
			printf "\n"
			gpt "Your name is now GLaDOS and mine is $USER, $T"
		fi
	fi
fi

#-----------------------CLASSIC MODE FUNCTION-----------------------
if [ -n "$T" ] && [ -z "$OP_C" ]; then
	if [ "$OP_N" = true ] && { [ "$OP_R" = true ] || [ ! -f ~/.config/tgpt/config.txt ]; }; then
		gpt "$T"
	elif [ -f ~/.config/tgpt/config.txt ]; then
		gpt "$T"
	elif [ ! -f ~/.config/tgpt/config.txt ]; then
		gpt "Your name is now GLaDOS and mine is $USER, $T"
	fi
fi

#-----------------------CHAT MODE LOOP-----------------------
while [ "$OP_C" = true ]; do
	printf "\n"
	stty echo
	printf "\e[0;1m>>\e[0m${blue}" && read -e -p " " q && tput sgr0
	stty -echo
	printf "\n"
	if [ "$q" = "-q" ]; then
		neofetch
		stty echo
		exit
	elif [ "$q" = "-h" ]; then
		cols=$(tput cols)
		printf "\n"
		for ((i=0; i<$cols; i++)); do printf "${magneta}-${normal}"; done && printf "\n"
		printf "$h\n\n"
		for ((i=0; i<$cols; i++)); do printf "${magneta}-${normal}"; done && printf "\n\n"
	elif [[ "$q" == -* ]]; then
		printf "${red}Command Not Found!\n${blue}Use '-h' to get more help\n"
	else
		gpt "$q"
	fi	
done

#HI, HOWYA DOING, LOOKING MY CODE, HUH? DON'T WORRY, U CAN COPY! IDC, HALF OF THE CODE ISN'T MINE LOL